# Generated by Django 3.2.4 on 2021-06-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_broadcastid_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastid',
            name='access_code',
            field=models.CharField(default='ashtewoihte', max_length=100),
            preserve_default=False,
        ),
    ]
